import React from 'react';
import styled from 'styled-components';
import Head from "next/head";
import { BoardHeader } from '../../components/Layout/BoardHeader';
import { SideBar } from 'src/components/Layout/Sidebar';
import { EmptyBoard } from 'src/components/EmptyBoard';

const Board = () => {
    const boardList = []
    return (
        <>
            <BoardHeader />
            <Wrapper>
                <Head>
                    <title>Board</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Container>
                    <SideBar />
                    {boardList.length===0 && <EmptyBoard/>  }
                </Container>
            </Wrapper>
        </>

    )
}

const Wrapper = styled.section`
width: 100%;
`;
const Container = styled.div`
display: flex;
`

export default Board;