import React from 'react';
import styled from 'styled-components';
import Head from "next/head";
import Image from 'next/image';
import Link from 'next/link';
import logo from '../../assets/icons/logo-dark.svg';
import moreIcon from '../../assets/icons/more-icon.svg';
import { customMedia } from 'styles/breakpoints';
import { useRouter } from "next/router";
import { StyleConstants } from 'styles/StylesConstants';

export const BoardHeader = () => {
    const router = useRouter();
    return (
        <Wrapper>
            <Head>
                <title>Board</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon/favicon.ico" />
            </Head>
            <Header>
                <div style={{ display: 'flex' }} className='logo-div'>
                <Link href="/home">
                <Image src={logo} alt='logo' className='logo' height={30}/>
                </Link>
                    <p className='page'>{router.pathname}</p>
                </div>
                <nav className='nav'>
                    <Link href="/home" >
                        <a className='account'>Account</a>
                    </Link>
                    <Image src={moreIcon} alt='more' width={30} height={15} />
                </nav>
            </Header>
        </Wrapper>
    )
}

const Wrapper = styled.section`
width: 100%;
padding: 0 20px;
background-color: ${StyleConstants.WHITE_COLOR};
z-index: 2;

${customMedia.lessThan("medium")`
      padding: 0 5px;
  `};
`;
const Header = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  .logo-div{
    justify-content: space-between;
    width: 25%;
    align-items: center;
    ${customMedia.lessThan("xlarge")`
        width: 35%;
  `};
      ${customMedia.lessThan("medium")`
        width: 60%;
  `};
  }
  .page{
    font-style: normal;
    font-weight: 700;
    font-size: 16px;
    font-family: 'Lobster', cursive;
    color: ${StyleConstants. MEDIUM_GREY_COLOR};
    line-height: 18px;
    align-self: end;
    ${customMedia.lessThan("medium")`
         font-size: 12px;
  `};
  }
  .account{
    font-family: 'Plus Jakarta Sans';
    font-style: normal;
    font-weight: 700;
    font-size: 15px;
    line-height: 19px;
    ${customMedia.lessThan("medium")`
         font-size: 12px;
  `};
  }
  .nav{
    width: 100px;
    display: flex:
    justify-content: space-between;
    align-items: center;
  }
`

